# Q3 Using Scikit-Learn

In [1]:
import numpy as np
import pandas as pd
import time
import gc
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [2]:
# Change to your GA Tech ID
ga_id = 'rpatro6'
# Requires a print() statement do not modify below print statement
print(903287114)

903287114


# Q3.1 Data Import and Cleansing Setup

In [3]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set. We've started this for you. 
# XXX

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('pulsar_stars.csv')
# -------------------------------

# XXX
# TODO: Separate out the x_data and y_data. We've started this for you.
# XXX

# -------------------------------
# ADD CODE HERE
# x_data = data.loc[]
# y_data = data.loc[]
x_data = data.loc[:, data.columns != "y"].to_numpy()
y_data = data.loc[:, "y"].to_numpy()
# -------------------------------


In [4]:
# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' 
# set to 614.
# 

# -------------------------------
# ADD CODE HERE
random_state = 614
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.3, random_state = random_state, shuffle=True)
# -------------------------------

# Q3.2 Linear Regression 

In [5]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
# 
linear = LinearRegression()
linear.fit(x_train, y_train)
# -------------------------------

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
print(accuracy_score(y_train, (linear.predict(x_train) + 0.5).astype(int)))
# Requires a print() statement
# -------------------------------

0.9720625798212005


In [7]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_test, (linear.predict(x_test) + 0.5).astype(int)))
# -------------------------------

0.9696461824953445


# Q3.3 Random Forest Classifier

In [8]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# Set 'random_state' to 614
# XXX

# -------------------------------
# ADD CODE HERE
random_state = 614
rf = RandomForestClassifier(random_state = random_state)
rf.fit(x_train, y_train)
# -------------------------------

C:\Users\rebec\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=614,
                       verbose=0, warm_start=False)

In [9]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_train, rf.predict(x_train)))
# -------------------------------

0.9968071519795658


In [10]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_test, rf.predict(x_test)))
# -------------------------------

0.9767225325884544


## Q3.3.1 Feature Importance

In [11]:
# XXX
# TODO: Determine the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
imp = rf.feature_importances_
print(imp)
# -------------------------------

[0.36631348 0.05096543 0.25857456 0.11768744 0.05862141 0.03806286
 0.05627799 0.05349682]


In [12]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(np.argsort(imp)[::-1])
# -------------------------------

[0 2 3 4 6 7 1 5]


## Q3.3.2 Hyper-parameter Tuning

In [13]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# 'n_estimators': [4, 16, 256]
# 'max_depth': [2, 8, 16]
# XXX

# -------------------------------
# ADD CODE HERE
n_estimators = [4, 16, 256]
max_depth = [2, 8, 16]
param_grid = {'n_estimators': n_estimators,'max_depth': max_depth}
# -------------------------------

In [14]:
# XXX
# TODO: Get the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
rf = RandomForestClassifier(random_state = random_state)
rf_random = GridSearchCV(estimator = rf, param_grid = param_grid, cv = 10)
rf_random.fit(x_train, y_train)
print(rf_random.best_params_)
# -------------------------------

{'max_depth': 16, 'n_estimators': 256}


In [15]:
# XXX
# TODO: Get the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(rf_random.best_score_)
# -------------------------------

0.9798850574712644


# Q3.4 Support Vector Machine

## Q3.4.1 Pre-process

In [16]:
# XXX
# TODO: Pre-process the data to standardize it, otherwise the grid search will take much longer.
# XXX

# -------------------------------
# ADD CODE HERE
x_norm_train = normalize(x_train)
x_norm_test = normalize(x_test)
# -------------------------------

## Q3.4.2 Classification

In [17]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
supportVM = SVC(gamma='auto')
supportVM.fit(x_norm_train, y_train)
# -------------------------------

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [18]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_train, supportVM.predict(x_norm_train)))
# -------------------------------

0.9694284802043422


In [19]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_test, supportVM.predict(x_norm_test)))
# -------------------------------

0.9662942271880819


## Q3.4.3 Hyper-parameter Tuning

In [20]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# 'kernel':('linear', 'rbf') 
# 'C':[0.01, 0.1, 1.0]
# XXX

# -------------------------------
# ADD CODE HERE
C = [0.01, 0.1, 1.0]
kernel = ['rbf', 'linear']
param_grid = {'C': C,'kernel': kernel}
#supportVM = SVC(gamma = 'auto')
#supportVM_random = GridSearchCV(estimator = supportVM, param_grid = param_grid, cv = 10)
#supportVM_random.fit(x_norm_train, y_train)
# -------------------------------

In [21]:
# XXX
# TODO: Get the best score, using .best_score_.
# Note: Set n_jobs=-1 and return_train_score=True
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
supportVM = SVC(gamma = 'auto')
supportVM_random1 = GridSearchCV(estimator = supportVM, param_grid = param_grid, cv = 10, n_jobs=-1,return_train_score=True )
supportVM_random1.fit(x_norm_train, y_train)
print(supportVM_random1.best_score_)
# -------------------------------

0.9722222222222222


In [22]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and standardization. 
# XXX

# -------------------------------
# ADD CODE HERE
print(accuracy_score(y_train, supportVM_random1.predict(x_norm_train)))
print(accuracy_score(y_test, supportVM_random1.predict(x_norm_test)))
# -------------------------------

0.9724616858237548
0.9702048417132216


In [23]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_train, supportVM_random1.predict(x_norm_train)))
# -------------------------------

0.9724616858237548


In [24]:
# XXX
# TODO: Test its accuracy (on the test set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(accuracy_score(y_test, supportVM_random1.predict(x_norm_test)))
# -------------------------------

0.9702048417132216




## Q3.4.4 Cross Validation Results 

In [25]:
# XXX
# TODO: Get the rank test score for all hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(supportVM_random1.cv_results_['rank_test_score'])
# -------------------------------

[6 5 4 3 2 1]


In [26]:
# XXX
# TODO: Get the mean testing score for all of hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX
# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(supportVM_random1.cv_results_['mean_test_score'])
# -------------------------------

[0.90844508 0.9548212  0.9589719  0.96607599 0.96886973 0.97222222]


# Q3.5 PCA

In [27]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# NOTE: Use the full x data set for this section 'x_data'

# -------------------------------
# ADD CODE HERE
# You should see an output here of PCA(copy=True....)
pca = PCA(n_components = 8, svd_solver = 'full')
pca.fit(x_data)
# -------------------------------

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [28]:
# XXX
# TODO: Get percentage of variance explained by each of the selected components
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(pca.explained_variance_ratio_)
# -------------------------------

[8.71053041e-01 7.81934383e-02 4.11562290e-02 6.15967691e-03
 2.43717952e-03 9.58578490e-04 3.90570992e-05 2.79968662e-06]


In [29]:
# XXX
# TODO: Get the singular values corresponding to each of the selected components.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(pca.singular_values_)
# -------------------------------

[14430.28004546  4323.5214088   3136.68022725  1213.47665361
   763.30168073   478.70316467    96.62788002    25.87063984]
